name: 3rd South
favicon: null
layout_spectrum: 0.50995
typography_spectrum: 0.51293
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'muscles & makeup'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090305'
    - '#f90525'
    - '#ff6a56'
    - '#a2a56e'
    - '#fff18e'
  brandStrength: 0.1875
  lightness: 0.9349313282873482
  saturation: 0.8125
  rhythmicContrast: 0.8923828513361514
purpose: []
