name: 3rd South
favicon: null
layout_spectrum: 0.50751
typography_spectrum: 0.62951
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'muscles & makeup'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#ffe500'
    - '#ffffff'
    - '#878787'
    - '#cbcbcb'
  brandStrength: 1
  lightness: 0.9349313282873482
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
