name: 3rd South
favicon: null
layout_spectrum: 0.51196
typography_spectrum: 0.57384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#737373'
    - '#0c0c0c'
    - '#c1c1c1'
    - '#383838'
  brandStrength: 0.125
  lightness: 0.9349313282873482
  saturation: 0.8125
  rhythmicContrast: 0.8923828513361514
purpose: []
