analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.51196
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.8125
  brandStrength: 0.125
  rhythmicContrast: 0.8923828513361514
  brandColors:
    - '#f7f7f7'
    - '#737373'
    - '#0c0c0c'
    - '#c1c1c1'
    - '#383838'
  lightness: 0.9349313282873482
purpose: []
favicon: null
name: 3rd South
typography_spectrum: 0.57384
