name: 3rd South
favicon: null
layout_spectrum: 0.50995
typography_spectrum: 0.50931
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'muscles & makeup'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#feffff'
    - '#a1a2a8'
    - '#761411'
    - '#816e50'
  brandStrength: 1
  lightness: 0.9349313282873482
  saturation: 0.8125
  rhythmicContrast: 0.8923828513361514
purpose: []
